In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('credit .csv')

In [3]:
df.duplicated().sum()

np.int64(1)

In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

age          2
job          6
marital      3
education    4
balance      0
housing      3
duration     2
campaign     0
approval     0
dtype: int64

In [7]:
df.dropna(inplace=True)

In [8]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
balance      0
housing      0
duration     0
campaign     0
approval     0
dtype: int64

In [9]:
df.dtypes

age          float64
job           object
marital       object
education     object
balance        int64
housing       object
duration     float64
campaign       int64
approval      object
dtype: object

In [10]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le=LabelEncoder()
df['job']=le.fit_transform(df['job'])

In [11]:
df['education']=le.fit_transform(df['education'])

In [12]:
df['marital']=le.fit_transform(df['marital'])

In [13]:
df['marital'].unique()

array([1, 2, 0])

In [14]:
# ohe=OneHotEncoder()
# df[['approval']]=ohe.fit_transform(df[['approval']])

In [15]:
df

,age,job,marital,education,balance,housing,duration,campaign,approval
0,30.0,10,1,0,1787,no,79.0,1,no
1,33.0,7,1,1,4789,yes,220.0,1,no
2,35.0,4,2,2,1350,yes,185.0,1,no
3,30.0,4,1,2,1476,yes,199.0,4,no
4,59.0,1,1,1,0,yes,226.0,1,no
...,...,...,...,...,...,...,...,...,...
4516,99.0,7,1,1,-333,yes,329.0,5,no
4517,57.0,6,1,2,-3313,yes,-153.0,1,no
4518,57.0,9,1,1,295,no,151.0,11,no
4519,28.0,1,1,1,1137,no,129.0,4,no
4520,44.0,2,2,2,1136,yes,345.0,2,no

In [16]:
df.dtypes

age          float64
job            int64
marital        int64
education      int64
balance        int64
housing       object
duration     float64
campaign       int64
approval      object
dtype: object

In [17]:
df['approval'].unique()

array(['no', 'yes'], dtype=object)

In [18]:
df['housing']=df['housing'].map({'yes':1, 'no':0})

In [19]:
df['approval']=df['approval'].map({'yes':1, 'no':0})

In [20]:
df

,age,job,marital,education,balance,housing,duration,campaign,approval
0,30.0,10,1,0,1787,0,79.0,1,0
1,33.0,7,1,1,4789,1,220.0,1,0
2,35.0,4,2,2,1350,1,185.0,1,0
3,30.0,4,1,2,1476,1,199.0,4,0
4,59.0,1,1,1,0,1,226.0,1,0
...,...,...,...,...,...,...,...,...,...
4516,99.0,7,1,1,-333,1,329.0,5,0
4517,57.0,6,1,2,-3313,1,-153.0,1,0
4518,57.0,9,1,1,295,0,151.0,11,0
4519,28.0,1,1,1,1137,0,129.0,4,0
4520,44.0,2,2,2,1136,1,345.0,2,0

In [21]:
df.to_csv('credit_cleaned.csv')

In [22]:
df=pd.read_csv('credit_cleaned.csv')

In [23]:
x=df.drop('approval',axis=1)
y=df['approval']

In [24]:
x

,Unnamed: 0,age,job,marital,education,balance,housing,duration,campaign
0,0,30.0,10,1,0,1787,0,79.0,1
1,1,33.0,7,1,1,4789,1,220.0,1
2,2,35.0,4,2,2,1350,1,185.0,1
3,3,30.0,4,1,2,1476,1,199.0,4
4,4,59.0,1,1,1,0,1,226.0,1
...,...,...,...,...,...,...,...,...,...
4495,4516,99.0,7,1,1,-333,1,329.0,5
4496,4517,57.0,6,1,2,-3313,1,-153.0,1
4497,4518,57.0,9,1,1,295,0,151.0,11
4498,4519,28.0,1,1,1,1137,0,129.0,4
4499,4520,44.0,2,2,2,1136,1,345.0,2

In [25]:
y

0       0
1       0
2       0
3       0
4       0
       ..
4495    0
4496    0
4497    0
4498    0
4499    0
Name: approval, Length: 4500, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [28]:
input_shape = x_train.shape[1]
input_shape

9

In [29]:
model=Sequential()
model.add(Dense(units=128, activation='relu', input_dim=(input_shape)))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))
model.add(Dense(units=8, activation='relu'))

model.add(Dense(units=1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

c:\Users\disha\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [30]:
model.fit(x_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8640 - loss: 1.3908
Epoch 2/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8976 - loss: 0.4363
Epoch 3/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8880 - loss: 0.3783
Epoch 4/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8782 - loss: 0.3892
Epoch 5/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8880 - loss: 0.3766
Epoch 6/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8927 - loss: 0.3512
Epoch 7/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8890 - loss: 0.3529
Epoch 8/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8733 - loss: 0.3850
Epoch 9/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8857 - loss: 0.3579
Epoch 10/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8859 - loss: 0.3365

In [31]:
pred=model.predict(x_test)

29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [34]:
pred=np.ravel(pred)

In [35]:
pred

array([3.10117304e-01, 6.13224991e-02, 1.34186158e-02, 1.80584088e-01,
       7.69539028e-02, 1.19665220e-01, 3.49643469e-01, 3.03004503e-01,
       3.10359932e-02, 1.24885716e-01, 2.84329712e-01, 6.57581538e-02,
       5.70827797e-02, 8.25133249e-02, 1.11490749e-01, 1.87786650e-02,
       1.70761436e-01, 1.01846159e-02, 2.75939733e-01, 3.49643469e-01,
       4.07462753e-02, 1.15748674e-01, 1.15042321e-01, 1.85286310e-02,
       1.26623670e-02, 1.58953547e-01, 3.49643469e-01, 2.56785750e-01,
       3.49643469e-01, 1.57807574e-01, 1.67000033e-02, 1.06394470e-01,
       2.26341397e-01, 9.13998857e-03, 7.15336064e-03, 1.45096602e-02,
       1.14151068e-01, 9.57537591e-02, 1.76042542e-02, 1.65768769e-02,
       3.49643469e-01, 1.57827914e-01, 3.05836260e-01, 1.91500470e-01,
       2.64718443e-01, 1.91045314e-01, 6.80079907e-02, 2.35660523e-02,
       3.48082721e-01, 2.38502681e-01, 5.57109416e-02, 9.63525549e-02,
       1.12601094e-01, 5.47784474e-03, 4.48403470e-02, 3.49643469e-01,
       9.62877870e-02, 3.36105525e-01, 3.49643469e-01, 1.09407827e-01,
       3.86566892e-02, 4.94338572e-02, 9.34438556e-02, 3.13596241e-02,
       3.49643469e-01, 1.94368549e-02, 3.49643469e-01, 3.49643469e-01,
       5.73695749e-02, 3.49643469e-01, 1.99946854e-02, 8.98988731e-03,
       9.25206095e-02, 2.39898801e-01, 5.62556721e-02, 1.92745373e-01,
       2.54471358e-02, 3.26468498e-01, 8.62100124e-02, 3.20901573e-02,
       1.84932187e-01, 2.07871780e-01, 1.76937282e-01, 6.68462068e-02,
       3.49643469e-01, 1.80940628e-01, 2.81267852e-01, 1.00902878e-01,
       1.22933559e-01, 1.91843249e-02, 3.49643469e-01, 5.40482961e-02,
       9.64341965e-03, 8.44819695e-02, 2.27522537e-01, 1.52184382e-01,
       1.11140825e-01, 6.03013895e-02, 4.37775739e-02, 1.24461845e-01,
       8.05259198e-02, 2.34218985e-01, 1.94012634e-02, 2.55416911e-02,
       1.78440809e-02, 3.49643469e-01, 1.12617441e-01, 3.02979425e-02,
       2.38600317e-02, 1.91656779e-02, 3.80362272e-02, 7.62146935e-02,
       3.45978469e-01, 1.39166892e-01, 5.30269034e-02, 1.26940450e-02,
       5.86648583e-02, 1.31881267e-01, 2.47117318e-02, 6.18900433e-02,
       2.42688194e-01, 2.39776634e-02, 8.31704140e-02, 4.28969488e-02,
       2.68089086e-01, 8.54433794e-03, 3.77809210e-03, 5.27097099e-02,
       1.64122954e-02, 2.00484525e-02, 1.54839948e-01, 3.49643469e-01,
       4.62572649e-02, 4.62426655e-02, 6.55054152e-02, 1.55898221e-02,
       1.63398325e-01, 3.56025696e-02, 2.84684747e-01, 1.57184117e-02,
       2.99465302e-02, 7.18028843e-02, 5.94906695e-03, 3.13470304e-01,
       1.46624878e-01, 9.13883187e-03, 1.37318969e-01, 2.57849395e-01,
       2.94821203e-01, 1.31035363e-02, 1.28561081e-02, 7.66643956e-02,
       2.13364676e-01, 2.83704791e-02, 2.12733075e-01, 5.48700429e-02,
       2.24066436e-01, 3.57917845e-02, 1.74156670e-02, 1.79648519e-01,
       3.49643469e-01, 8.95505846e-02, 1.59857005e-01, 7.30114337e-03,
       7.83695281e-02, 3.16489935e-02, 1.37793170e-02, 1.30036056e-01,
       1.85331300e-01, 1.39565235e-02, 4.53182980e-02, 2.05494255e-01,
       2.53497481e-01, 5.40315267e-03, 4.91409078e-02, 2.53746480e-01,
       2.74919043e-03, 1.25159368e-01, 1.45631820e-01, 2.00021677e-02,
       9.83013399e-03, 2.06062552e-02, 2.56712046e-02, 2.53802627e-01,
       4.46755476e-02, 8.91835764e-02, 5.99639267e-02, 2.00893909e-01,
       1.63542286e-01, 4.66779396e-02, 9.30999443e-02, 3.30981314e-01,
       7.91917518e-02, 1.25258401e-01, 1.79436263e-02, 6.56291842e-03,
       3.49643469e-01, 4.33911495e-02, 9.25228093e-03, 5.74947260e-02,
       6.06697313e-02, 1.52063489e-01, 3.49643469e-01, 8.45296122e-03,
       7.15854913e-02, 3.49643469e-01, 1.17739253e-01, 2.89178826e-02,
       9.68985353e-03, 3.77296209e-02, 1.38055414e-01, 3.49643469e-01,
       2.80104101e-01, 3.49643469e-01, 3.50558162e-02, 3.31287563e-01,
       8.21377710e-02, 3.43509763e-01, 5.10102063e-02, 1.55119091e-01,
       1.70600787e-02, 4.29514758e-02, 3.54822315e-02, 2.09837481e-02,
       1.41591012e-01, 3.49643469e-01, 1.47956628e-02, 5.89132868e-02,
       1.69242367e-01, 3.18486989e-01, 1.90772545e-02, 1.62444413e-02,
       2.94236183e-01, 3.40186924e-01, 1.34555455e-02, 1.33238677e-02,
       1.90826040e-02, 2.91328412e-02, 1.13249555e-01, 3.49643469e-01,
       1.66315988e-01, 4.61329333e-02, 1.28218411e-02, 2.51418427e-02,
       2.04669479e-02, 3.49643469e-01, 1.58524867e-02, 3.49643469e-01,
       1.29327849e-01, 5.82575910e-02, 5.12609407e-02, 1.71307307e-02,
       1.00386031e-01, 1.50394335e-01, 2.59083621e-02, 2.42190719e-01,
       3.42037454e-02, 4.31842916e-02, 9.18075893e-05, 2.05748096e-01,
       5.67112193e-02, 3.49643469e-01, 3.49643469e-01, 2.19452888e-01,
       6.96345940e-02, 5.04002236e-02, 2.41036847e-01, 3.48521531e-01,
       2.40588597e-38, 5.63286766e-02, 1.26303554e-01, 3.49643469e-01,
       1.86319258e-02, 3.49643469e-01, 9.07218922e-03, 2.96104193e-01,
       2.47110009e-01, 4.70202714e-02, 3.49643469e-01, 3.54580544e-02,
       2.24458184e-02, 6.21188730e-02, 3.49643469e-01, 1.41471192e-01,
       1.03769109e-01, 1.00046173e-01, 1.93698987e-01, 3.49643469e-01,
       1.47242486e-01, 5.56147583e-02, 2.95055807e-01, 2.01367941e-02,
       2.84705669e-01, 1.07140623e-01, 1.46929617e-03, 8.91182106e-03,
       2.07250938e-02, 6.34398311e-02, 2.33781431e-02, 9.37341480e-04,
       3.49643469e-01, 2.93608606e-01, 2.53300756e-01, 3.32208276e-02,
       2.15125903e-01, 1.06072024e-01, 3.49643469e-01, 3.82461213e-02,
       1.73266575e-01, 6.29310356e-03, 2.84315739e-03, 2.45313913e-01,
       9.76602882e-02, 3.49643469e-01, 9.29760933e-02, 1.63175240e-01,
       2.65758157e-01, 3.37840497e-01, 5.32481857e-02, 7.83600844e-03,
       9.07464623e-02, 3.49643469e-01, 1.29514754e-01, 1.75853834e-01,
       1.57169804e-01, 1.46661205e-02, 4.64441776e-02, 3.34205106e-02,
       3.33060473e-01, 2.53455061e-02, 6.02699292e-04, 1.13988638e-01,
       4.43118475e-02, 2.04187080e-01, 2.44590998e-01, 7.08941519e-02,
       5.01680784e-02, 1.39223173e-01, 1.88919216e-01, 3.26823860e-01,
       2.30666891e-01, 5.00620715e-03, 3.49643469e-01, 1.59157053e-01,
       3.49643469e-01, 8.96285847e-03, 3.49643469e-01, 3.49643469e-01,
       4.48421463e-02, 1.72518566e-01, 3.49643469e-01, 5.69265895e-02,
       1.49018969e-02, 6.46378398e-02, 1.67231977e-01, 5.03362380e-02,
       7.27782398e-02, 7.53643066e-02, 3.93215269e-02, 1.52057096e-01,
       3.49643469e-01, 2.49657240e-02, 3.49643469e-01, 3.25811774e-01,
       1.89126313e-01, 3.13868999e-01, 1.07931271e-01, 3.49643469e-01,
       1.12430025e-02, 3.22202325e-01, 2.37501264e-01, 6.01826198e-02,
       1.12814538e-01, 4.41449992e-02, 8.10601413e-02, 2.68103153e-01,
       3.16913456e-01, 2.55580377e-02, 1.58248618e-01, 2.15815395e-01,
       6.08591847e-02, 2.14958400e-01, 1.58002730e-02, 2.24859025e-02,
       1.92317471e-01, 3.09105925e-02, 3.49643469e-01, 1.23320721e-01,
       2.44238060e-02, 3.49643469e-01, 2.86971740e-02, 1.50717124e-01,
       2.11382195e-01, 2.19870538e-01, 3.49643469e-01, 8.01720619e-02,
       2.87139863e-01, 1.18373491e-01, 3.27448472e-02, 6.28242195e-02,
       4.01297845e-02, 3.49643469e-01, 6.05107918e-02, 2.74069700e-02,
       2.36192971e-01, 2.78325975e-01, 1.79440573e-01, 3.80171947e-02,
       1.30640306e-02, 3.49643469e-01, 8.24883431e-02, 3.49643469e-01,
       2.44979020e-02, 1.39071807e-01, 3.30339909e-01, 6.51098415e-02,
       3.27667110e-02, 2.99278080e-01, 2.02089489e-01, 2.03053266e-01,
       1.92624256e-02, 2.84243487e-02, 6.95882291e-02, 3.67263667e-02,
       3.49643469e-01, 7.72788450e-02, 2.62198687e-01, 4.92625535e-02,
       3.49643469e-01, 3.49643469e-01, 1.25560239e-01, 2.75195539e-01,
       3.33536625e-01, 2.03072699e-03, 1.70855653e-02, 1.46617536e-02,
       5.62280230e-02, 1.14081334e-02, 2.29267865e-01, 2.74990480e-02,
       2.81890910e-02, 2.28947625e-01, 1.05358243e-01, 4.50186320e-02,
       3.00479740e-01, 2.32175171e-01, 2.68673658e-01, 1.26528982e-02,
       1.32598663e-02, 2.63653606e-01, 2.25799114e-01, 9.42998100e-03,
       1.28535032e-01, 2.05318257e-01, 1.47691011e-01, 1.64316297e-01,
       6.68357238e-02, 1.47924181e-02, 1.34793343e-02, 3.69828939e-02,
       1.58087611e-01, 1.08405098e-01, 4.81550284e-02, 5.26498593e-02,
       1.12301512e-02, 3.49643469e-01, 2.84257293e-01, 3.49643469e-01,
       4.98890993e-04, 6.94701001e-02, 2.08525389e-01, 2.01429635e-01,
       3.49643469e-01, 2.92592376e-01, 1.50434271e-01, 3.08938950e-01,
       3.49643469e-01, 3.54108252e-02, 3.49643469e-01, 1.92362387e-02,
       3.49643469e-01, 4.35547158e-02, 1.10230744e-02, 7.28310421e-02,
       1.97134599e-01, 2.83591207e-02, 3.32351357e-01, 3.14648420e-01,
       2.85378098e-01, 1.86847558e-06, 3.49643469e-01, 1.19530343e-01,
       1.88807592e-01, 1.59174234e-01, 6.76862895e-02, 2.46283337e-01,
       3.79215255e-02, 5.17742969e-02, 3.73099907e-03, 6.17068075e-02,
       1.12675540e-01, 3.49643469e-01, 1.83425054e-01, 3.23790550e-01,
       1.55937448e-02, 2.81859934e-02, 3.49643469e-01, 1.58217158e-02,
       5.07333092e-02, 4.73319739e-02, 2.22426071e-03, 3.49643469e-01,
       1.20741449e-01, 3.42495292e-01, 1.71069399e-01, 8.74666646e-02,
       3.11600298e-01, 2.97653049e-01, 1.51908517e-01, 3.49643469e-01,
       1.80651695e-01, 1.01332955e-01, 1.47859290e-01, 6.18516169e-02,
       4.28823791e-02, 1.04889926e-02, 3.49643469e-01, 2.34325737e-01,
       3.49643469e-01, 2.94598937e-01, 2.74248481e-01, 9.14717689e-02,
       7.84422830e-03, 1.88534111e-02, 1.08930513e-01, 7.30603263e-02,
       2.39684090e-01, 2.99239308e-01, 2.22308058e-02, 2.46149510e-01,
       1.73168834e-02, 5.29740155e-02, 1.90567182e-04, 1.95360824e-01,
       2.38477681e-02, 3.07341635e-01, 9.39761251e-02, 8.20791796e-02,
       2.69228578e-01, 2.61709988e-01, 3.49775627e-02, 3.49643469e-01,
       5.85544948e-03, 1.50024891e-01, 1.57215873e-05, 9.23157781e-02,
       8.23479705e-03, 3.30436110e-01, 3.25486511e-02, 2.36303762e-01,
       3.36100496e-02, 1.43337417e-02, 5.24542294e-02, 6.74304888e-02,
       3.46684068e-01, 7.61557147e-02, 1.41193807e-01, 1.96042463e-01,
       2.21858516e-01, 2.11517587e-02, 2.22080097e-01, 1.38956651e-01,
       2.26109982e-01, 6.95109525e-09, 8.36687256e-03, 1.19055301e-01,
       5.49710579e-02, 8.76410753e-02, 4.48925905e-02, 1.13795660e-01,
       5.69922365e-02, 3.84661332e-02, 2.59734333e-01, 3.70559096e-02,
       1.39704281e-02, 1.77891940e-01, 5.57271391e-02, 8.61315727e-02,
       3.49643469e-01, 7.04892948e-02, 1.04587469e-02, 2.32745111e-01,
       1.33173373e-02, 5.27897067e-02, 2.97602028e-01, 8.60986263e-02,
       3.49643469e-01, 1.25813186e-01, 2.01664641e-02, 1.12418078e-01,
       2.35449690e-02, 2.54763551e-02, 2.76316732e-01, 1.83045398e-02,
       3.49643469e-01, 2.02882111e-01, 2.91073862e-02, 7.83199817e-03,
       2.43960500e-01, 1.38945431e-02, 1.14146493e-01, 1.12004764e-01,
       3.49643469e-01, 1.73734248e-01, 4.80821505e-02, 6.46805689e-02,
       2.20304832e-01, 2.45845512e-01, 8.23749751e-02, 9.12131816e-02,
       4.01142873e-02, 1.37086183e-01, 2.85602733e-02, 7.86790550e-02,
       3.49643469e-01, 2.14036629e-01, 5.54433875e-02, 1.02878109e-01,
       2.55549643e-02, 8.45269710e-02, 2.69728541e-01, 1.09408997e-01,
       3.49643469e-01, 2.47618005e-01, 3.49643469e-01, 1.54071048e-01,
       1.12292496e-02, 4.05570865e-02, 8.05101022e-02, 2.30034366e-01,
       4.96037630e-03, 3.49643469e-01, 1.59674734e-01, 1.17042139e-01,
       5.13675511e-02, 6.30575195e-02, 1.80252641e-01, 1.41108349e-01,
       8.38237926e-02, 9.20332298e-02, 7.92017356e-02, 6.52400851e-02,
       3.52862030e-02, 7.59734074e-03, 5.77212907e-02, 2.30861217e-01,
       9.01710391e-02, 2.14714631e-02, 2.37660520e-02, 3.24599519e-02,
       1.16879947e-01, 1.44360708e-02, 2.48635970e-02, 2.09666520e-01,
       3.26794758e-02, 1.75435990e-02, 3.49643469e-01, 1.06114484e-01,
       2.60550668e-03, 3.27680521e-02, 3.61884385e-02, 8.45447481e-02,
       1.87248245e-01, 3.16293016e-02, 1.37638701e-02, 1.04644872e-01,
       1.16041824e-01, 2.18442962e-01, 3.49643469e-01, 1.60469208e-02,
       2.48620942e-01, 2.42205888e-01, 1.79116279e-01, 4.97356839e-02,
       9.80421230e-02, 1.64556906e-01, 1.75181612e-01, 1.41814083e-01,
       3.49643469e-01, 3.49643469e-01, 1.59362778e-01, 1.70738287e-02,
       1.70478560e-02, 3.28350753e-01, 5.65960407e-02, 5.07750437e-02,
       1.70562059e-01, 9.97900292e-02, 8.76676012e-03, 5.62911592e-02,
       3.49643469e-01, 1.35089174e-01, 3.08631957e-01, 6.75062016e-02,
       3.98137514e-03, 1.63369536e-01, 1.05310455e-01, 6.10063560e-02,
       4.78682220e-02, 2.17208743e-01, 8.71547684e-03, 1.69903293e-01,
       2.77974725e-01, 5.30710071e-02, 7.79547170e-02, 3.21662813e-01,
       3.84403467e-02, 7.74163827e-02, 1.76912174e-01, 8.87221992e-02,
       6.49441630e-02, 1.77184969e-01, 2.85441011e-01, 1.82863995e-02,
       1.31408703e-02, 3.49643469e-01, 2.98404340e-02, 2.96421438e-01,
       2.64285225e-02, 3.23172472e-02, 7.95052797e-02, 9.62023214e-02,
       3.49643469e-01, 6.73112571e-02, 3.49643469e-01, 1.03332400e-01,
       7.38096312e-02, 1.51759367e-02, 8.59514922e-02, 1.66124068e-02,
       3.02739888e-01, 2.20029950e-01, 1.33445524e-02, 3.09431553e-02,
       1.86792642e-01, 9.14266855e-02, 9.50032547e-02, 1.40813917e-01,
       2.00315222e-01, 3.14299732e-01, 1.10678948e-01, 4.74314094e-02,
       8.17829818e-02, 3.49643469e-01, 3.34603399e-01, 1.51237166e-02,
       6.53902302e-03, 3.49643469e-01, 7.03271776e-02, 1.84807986e-01,
       9.22052376e-03, 3.49643469e-01, 2.07922786e-01, 2.25437023e-02,
       2.04059392e-01, 3.33878279e-01, 2.50474244e-01, 1.13113336e-02,
       2.10123956e-02, 3.49643469e-01, 3.26727748e-01, 1.63524136e-01,
       1.10778652e-01, 2.86477841e-02, 1.37170807e-01, 2.17906479e-02,
       3.10441609e-02, 3.49643469e-01, 5.38255945e-02, 2.83798724e-01,
       3.49643469e-01, 7.33765736e-02, 3.49643469e-01, 3.01662564e-01,
       3.49643469e-01, 3.89914028e-02, 3.49643469e-01, 4.05412279e-02,
       2.64306162e-02, 4.29326259e-02, 1.44945448e-02, 9.82629694e-03,
       3.49643469e-01, 4.55903634e-02, 2.17405543e-01, 1.38503104e-01,
       7.45771527e-02, 2.26687416e-02, 6.87289424e-03, 4.34515849e-02,
       3.21766473e-02, 2.77411252e-01, 1.00145437e-01, 1.65349513e-01,
       6.22414239e-02, 2.64614299e-02, 6.33764416e-02, 3.49643469e-01,
       3.49643469e-01, 2.29140855e-02, 3.49643469e-01, 3.49643469e-01,
       2.95668263e-02, 9.12680253e-02, 1.15473233e-01, 1.26372520e-02,
       1.86032187e-02, 3.46614756e-02, 1.65155791e-02, 1.10607184e-01,
       2.33417451e-01, 3.49643469e-01, 1.40039727e-01, 2.81916553e-04,
       3.49643469e-01, 1.07823417e-01, 2.58262232e-02, 3.34411091e-03,
       6.87548250e-04, 1.36507943e-01, 2.89972663e-01, 4.56745438e-02,
       8.16867948e-02, 4.31406386e-02, 3.57736200e-02, 3.43320221e-02,
       1.47326350e-01, 2.25118905e-01, 2.82392073e-02, 1.71048963e-03,
       1.56243341e-02, 3.49643469e-01, 1.60102677e-02, 2.77586514e-04,
       1.48217306e-02, 1.30841257e-02, 3.22790325e-01, 2.32705604e-02,
       1.81386501e-01, 1.94570720e-02, 2.40407839e-01, 7.49624334e-04,
       2.07387740e-04, 8.78291246e-07, 3.85913253e-02, 3.49643469e-01,
       8.20259154e-02, 3.49643469e-01, 3.89425419e-02, 1.90024719e-01,
       1.40343793e-02, 6.17375560e-02, 1.26536908e-02, 6.08287565e-02,
       5.25275357e-02, 2.47034375e-02, 3.49643469e-01, 3.49643469e-01,
       7.33274817e-02, 1.76752792e-06, 4.25651297e-02, 4.98448126e-02,
       2.63540685e-01, 4.70306017e-02, 2.39817277e-01, 3.60934287e-02,
       8.70064646e-02, 4.10203785e-02, 1.42006539e-02, 1.24524973e-01,
       2.31776297e-01, 2.35050455e-01, 1.20858140e-02, 3.30991223e-02,
       5.08056842e-02, 1.65021792e-01, 3.35217535e-01, 2.83822208e-03,
       1.51250988e-01, 1.61246553e-01, 6.86077576e-04, 6.21694536e-14,
       6.64776517e-03, 6.77912217e-03, 3.12467784e-01, 3.49643469e-01,
       1.57208622e-01, 1.17986649e-01, 1.89479552e-02, 7.60391541e-03],
      dtype=float32)

In [36]:
y_test

2323    1
3686    0
2974    1
2992    1
468     1
       ..
911     0
809     0
2940    1
3710    0
3257    0
Name: approval, Length: 900, dtype: int64

In [37]:
output=pd.DataFrame({'Actual': y_test, 'Prediction':(pred>=0.5).astype(int)})

In [38]:
output

      Actual  Prediction
2323       1           0
3686       0           0
2974       1           0
2992       1           0
468        1           0
...      ...         ...
911        0           0
809        0           0
2940       1           0
3710       0           0
3257       0           0

[900 rows x 2 columns]

In [39]:
loss, accuracy = model.evaluate(x_test, y_test)
print(f'Test Accuracy: {accuracy:.4f}')

29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8825 - loss: 0.3722
Test Accuracy: 0.8878

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, (pred>=0.5).astype(int)))
print(confusion_matrix(y_test, (pred>=0.5).astype(int))) 

#this will show how well the model is performing on the test data

              precision    recall  f1-score   support

           0       0.89      1.00      0.94       799
           1       0.00      0.00      0.00       101

    accuracy                           0.89       900
   macro avg       0.44      0.50      0.47       900
weighted avg       0.79      0.89      0.84       900

[[799   0]
 [101   0]]

c:\Users\disha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\disha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\disha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])