In [3]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('credit .csv')

In [5]:
df.duplicated().sum()

np.int64(1)

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.isnull().sum()

age          2
job          6
marital      3
education    4
balance      0
housing      3
duration     2
campaign     0
approval     0
dtype: int64

In [9]:
df.dropna(inplace=True)

In [10]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
balance      0
housing      0
duration     0
campaign     0
approval     0
dtype: int64

In [11]:
df.dtypes

age          float64
job           object
marital       object
education     object
balance        int64
housing       object
duration     float64
campaign       int64
approval      object
dtype: object

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le=LabelEncoder()
df['job']=le.fit_transform(df['job'])

In [13]:
df['education']=le.fit_transform(df['education'])

In [14]:
df['marital']=le.fit_transform(df['marital'])

In [15]:
df['marital'].unique()

array([1, 2, 0])

In [16]:
# ohe=OneHotEncoder()
# df[['approval']]=ohe.fit_transform(df[['approval']])

In [17]:
df

,age,job,marital,education,balance,housing,duration,campaign,approval
0,30.0,10,1,0,1787,no,79.0,1,no
1,33.0,7,1,1,4789,yes,220.0,1,no
2,35.0,4,2,2,1350,yes,185.0,1,no
3,30.0,4,1,2,1476,yes,199.0,4,no
4,59.0,1,1,1,0,yes,226.0,1,no
...,...,...,...,...,...,...,...,...,...
4516,99.0,7,1,1,-333,yes,329.0,5,no
4517,57.0,6,1,2,-3313,yes,-153.0,1,no
4518,57.0,9,1,1,295,no,151.0,11,no
4519,28.0,1,1,1,1137,no,129.0,4,no
4520,44.0,2,2,2,1136,yes,345.0,2,no

In [18]:
df.dtypes

age          float64
job            int64
marital        int64
education      int64
balance        int64
housing       object
duration     float64
campaign       int64
approval      object
dtype: object

In [19]:
df['approval'].unique()

array(['no', 'yes'], dtype=object)

In [20]:
df['housing']=df['housing'].map({'yes':1, 'no':0})

In [21]:
df['approval']=df['approval'].map({'yes':1, 'no':0})

In [22]:
df

,age,job,marital,education,balance,housing,duration,campaign,approval
0,30.0,10,1,0,1787,0,79.0,1,0
1,33.0,7,1,1,4789,1,220.0,1,0
2,35.0,4,2,2,1350,1,185.0,1,0
3,30.0,4,1,2,1476,1,199.0,4,0
4,59.0,1,1,1,0,1,226.0,1,0
...,...,...,...,...,...,...,...,...,...
4516,99.0,7,1,1,-333,1,329.0,5,0
4517,57.0,6,1,2,-3313,1,-153.0,1,0
4518,57.0,9,1,1,295,0,151.0,11,0
4519,28.0,1,1,1,1137,0,129.0,4,0
4520,44.0,2,2,2,1136,1,345.0,2,0

In [23]:
df.to_csv('credit_cleaned.csv')

In [24]:
df=pd.read_csv('credit_cleaned.csv')

In [25]:
x=df.drop('approval',axis=1)
y=df['approval']

In [26]:
x

,Unnamed: 0,age,job,marital,education,balance,housing,duration,campaign
0,0,30.0,10,1,0,1787,0,79.0,1
1,1,33.0,7,1,1,4789,1,220.0,1
2,2,35.0,4,2,2,1350,1,185.0,1
3,3,30.0,4,1,2,1476,1,199.0,4
4,4,59.0,1,1,1,0,1,226.0,1
...,...,...,...,...,...,...,...,...,...
4495,4516,99.0,7,1,1,-333,1,329.0,5
4496,4517,57.0,6,1,2,-3313,1,-153.0,1
4497,4518,57.0,9,1,1,295,0,151.0,11
4498,4519,28.0,1,1,1,1137,0,129.0,4
4499,4520,44.0,2,2,2,1136,1,345.0,2

In [27]:
y

0       0
1       0
2       0
3       0
4       0
       ..
4495    0
4496    0
4497    0
4498    0
4499    0
Name: approval, Length: 4500, dtype: int64

In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [30]:
input_shape = x_train.shape[1]
input_shape

9

In [31]:
model=Sequential()
model.add(Dense(units=128, activation='relu', input_dim=(input_shape)))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))
model.add(Dense(units=8, activation='relu'))

model.add(Dense(units=1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

c:\Users\disha\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [32]:
model.fit(x_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5937 - loss: 25.3555
Epoch 2/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8168 - loss: 0.8976
Epoch 3/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8824 - loss: 0.5338
Epoch 4/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8842 - loss: 0.5760
Epoch 5/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8710 - loss: 0.6049
Epoch 6/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8932 - loss: 0.3714
Epoch 7/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8806 - loss: 0.3823
Epoch 8/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8843 - loss: 0.3725
Epoch 9/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8887 - loss: 0.3686
Epoch 10/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8875 - loss: 0.3538

In [33]:
pred=model.predict(x_test)

29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [34]:
pred=np.ravel(pred)

In [35]:
pred

array([2.55588442e-01, 1.04880288e-01, 6.21331260e-02, 2.58898497e-01,
       3.12161446e-01, 1.88979372e-01, 3.73050630e-01, 3.65983695e-01,
       7.00188354e-02, 9.75028127e-02, 3.69960696e-01, 7.03337118e-02,
       1.04748726e-01, 1.16812631e-01, 1.41239315e-01, 3.44194099e-02,
       3.12903941e-01, 1.38479322e-02, 2.16181025e-01, 3.73050630e-01,
       8.34292620e-02, 1.21685423e-01, 1.50392398e-01, 1.92606878e-02,
       2.11480912e-02, 2.13142037e-01, 3.73050630e-01, 2.77641684e-01,
       3.43149722e-01, 2.10528240e-01, 2.49399301e-02, 8.06396902e-02,
       3.17736953e-01, 8.49340670e-03, 2.01333035e-02, 3.26658078e-02,
       1.79667801e-01, 1.83208093e-01, 4.15783711e-02, 1.14377819e-01,
       3.73050630e-01, 3.20111781e-01, 3.14536572e-01, 1.33967116e-01,
       3.07213098e-01, 3.20272595e-01, 1.18096396e-01, 2.93628145e-02,
       3.73050630e-01, 3.49078029e-01, 1.05129421e-01, 7.89066702e-02,
       1.35897696e-01, 1.12699755e-01, 5.45243993e-02, 3.73050630e-01,
       3.73050630e-01, 3.73050630e-01, 3.55682254e-01, 1.41702741e-01,
       6.71000853e-02, 7.63803869e-02, 1.52800560e-01, 1.82052657e-01,
       3.70026112e-01, 1.72589973e-01, 3.73050630e-01, 3.73050630e-01,
       1.08880192e-01, 3.73050630e-01, 1.64518692e-02, 1.77359745e-01,
       1.24276184e-01, 3.07480723e-01, 8.41255486e-02, 2.82354534e-01,
       4.67290580e-02, 3.73050630e-01, 7.27360472e-02, 6.35349676e-02,
       1.43879294e-01, 3.39654088e-01, 1.81177467e-01, 2.29758799e-01,
       3.73050630e-01, 3.28073710e-01, 3.17396075e-01, 1.21769600e-01,
       1.48499742e-01, 3.79212946e-02, 3.73050630e-01, 7.34935328e-02,
       9.09164920e-03, 1.33099630e-01, 2.46069968e-01, 2.99182206e-01,
       8.81102830e-02, 1.12873353e-01, 7.38291293e-02, 1.88279286e-01,
       1.19099438e-01, 2.10943475e-01, 4.08108942e-02, 5.67506440e-02,
       3.22926417e-02, 3.73050630e-01, 1.06095120e-01, 2.83046849e-02,
       2.21586511e-01, 4.43935916e-02, 6.67304546e-02, 9.72943604e-02,
       3.68587464e-01, 2.04857439e-01, 9.30590928e-02, 1.08213481e-02,
       4.87110913e-02, 1.03845499e-01, 2.65459213e-02, 8.31329972e-02,
       3.41103196e-01, 5.12678027e-02, 1.42389163e-01, 6.73439130e-02,
       3.09943706e-01, 1.55313006e-02, 7.33013824e-02, 1.14144035e-01,
       3.25468220e-02, 6.65324479e-02, 2.20817506e-01, 3.73050630e-01,
       2.84558356e-01, 6.98852539e-02, 1.43056005e-01, 1.38068376e-02,
       2.51601428e-01, 4.30825204e-02, 3.58127505e-01, 2.09534451e-01,
       2.46217772e-02, 8.19817781e-02, 1.15835190e-01, 3.73050630e-01,
       3.50004137e-01, 1.41687393e-01, 7.55662099e-02, 2.67280966e-01,
       3.57349753e-01, 1.46629522e-02, 1.33840675e-02, 2.67523378e-01,
       2.92220742e-01, 2.64105927e-02, 2.97893584e-01, 1.08365282e-01,
       1.57997027e-01, 3.72671932e-01, 3.73050630e-01, 1.62593558e-01,
       3.73050630e-01, 1.38140768e-01, 9.03559774e-02, 8.39935895e-03,
       1.26821861e-01, 3.81671600e-02, 2.59762648e-02, 1.63000152e-01,
       3.73050630e-01, 1.50422901e-02, 7.94476718e-02, 2.06132516e-01,
       3.23056310e-01, 1.38690602e-02, 2.83816814e-01, 3.17151874e-01,
       8.84991214e-02, 1.90433562e-01, 2.19799370e-01, 1.60873421e-02,
       1.74833149e-01, 1.90951396e-02, 4.72899973e-02, 2.67174602e-01,
       8.78284052e-02, 9.80321020e-02, 2.40331769e-01, 3.14412862e-01,
       2.37643048e-01, 2.42811471e-01, 3.56065154e-01, 3.73050630e-01,
       4.98330407e-02, 1.81170374e-01, 1.97384935e-02, 1.26549125e-01,
       3.73050630e-01, 7.80967101e-02, 1.10396370e-02, 2.87923485e-01,
       1.86696231e-01, 2.36108348e-01, 3.73050630e-01, 1.37346573e-02,
       7.25164786e-02, 3.73050630e-01, 9.34621096e-02, 4.53628264e-02,
       1.06419332e-01, 4.87483144e-02, 3.26045960e-01, 3.59112710e-01,
       1.21790916e-01, 3.73050630e-01, 2.28766322e-01, 3.70630264e-01,
       9.60051194e-02, 3.69321555e-01, 5.69734275e-02, 2.17068627e-01,
       1.16884047e-02, 8.22805315e-02, 7.14202076e-02, 2.82977205e-02,
       2.16475412e-01, 3.73050630e-01, 2.23131329e-02, 5.51534966e-02,
       3.07005823e-01, 3.68129343e-01, 3.02437320e-02, 2.10180581e-02,
       2.23516792e-01, 3.73050630e-01, 1.53015899e-02, 2.69034747e-02,
       4.51479778e-02, 2.58071367e-02, 1.80425107e-01, 3.73050630e-01,
       2.38910705e-01, 1.35469481e-01, 2.49850042e-02, 2.81807743e-02,
       1.57867763e-02, 3.73050630e-01, 1.34278685e-02, 3.73050630e-01,
       1.98057085e-01, 2.77788550e-01, 2.41212726e-01, 1.81492969e-01,
       5.79602234e-02, 2.20912114e-01, 2.35885695e-01, 2.78827816e-01,
       9.68626440e-02, 3.72790098e-02, 6.70237988e-02, 2.88677573e-01,
       5.88625558e-02, 3.73050630e-01, 3.73050630e-01, 3.63259256e-01,
       9.81385484e-02, 6.44455776e-02, 3.42517287e-01, 2.12771341e-01,
       1.35110065e-04, 9.91424844e-02, 9.36169252e-02, 3.73050630e-01,
       3.51414889e-01, 3.73050630e-01, 4.30587865e-02, 3.65758717e-01,
       3.42568815e-01, 8.64354745e-02, 3.51669818e-01, 3.73664871e-02,
       3.73050630e-01, 1.16891183e-01, 3.73050630e-01, 7.90776089e-02,
       1.10708080e-01, 1.31902069e-01, 2.31780678e-01, 3.73050630e-01,
       2.07883000e-01, 7.55009726e-02, 2.99953818e-01, 4.66699786e-02,
       3.68089557e-01, 1.29897162e-01, 6.25819936e-02, 1.06207728e-02,
       1.59254298e-01, 7.02430382e-02, 1.98268026e-01, 1.09785713e-01,
       3.73050630e-01, 5.93794227e-01, 3.19109112e-01, 6.10706434e-02,
       3.07758719e-01, 1.01968691e-01, 3.73050630e-01, 2.62468517e-01,
       2.33826160e-01, 2.15367749e-01, 9.54346284e-02, 3.52666944e-01,
       1.36009604e-01, 3.73050630e-01, 3.42474937e-01, 1.18887067e-01,
       2.12688357e-01, 3.71173203e-01, 1.01756819e-01, 8.16308614e-03,
       1.34526536e-01, 3.73050630e-01, 1.92829728e-01, 2.31761709e-01,
       2.04363599e-01, 1.90082267e-02, 4.98320460e-02, 3.82786654e-02,
       3.73050630e-01, 4.77636643e-02, 3.73050630e-01, 8.66203234e-02,
       2.47793585e-01, 2.85504192e-01, 3.35902482e-01, 6.90248981e-02,
       7.99402297e-02, 2.12851152e-01, 3.34808618e-01, 3.73050630e-01,
       3.43695819e-01, 1.40893728e-01, 3.73050630e-01, 2.05366388e-01,
       3.73050630e-01, 1.03622833e-02, 3.73050630e-01, 3.73050630e-01,
       1.13656715e-01, 1.53384671e-01, 3.73050630e-01, 9.91693586e-02,
       2.39924658e-02, 5.71464524e-02, 1.76230937e-01, 8.75134170e-02,
       8.36119726e-02, 1.01734392e-01, 3.48696485e-02, 2.20215559e-01,
       2.23652631e-01, 2.48082280e-02, 3.73050630e-01, 3.71755570e-01,
       2.10003912e-01, 1.75958499e-01, 3.73050630e-01, 3.73050630e-01,
       2.68957485e-02, 3.62115115e-01, 3.73050630e-01, 6.69224337e-02,
       1.64442703e-01, 4.41327319e-02, 1.19704776e-01, 3.41306835e-01,
       3.73050630e-01, 4.21341956e-02, 2.32557997e-01, 3.11460316e-01,
       5.10633625e-02, 2.69181669e-01, 2.32261829e-02, 1.56625230e-02,
       2.73886353e-01, 4.66356240e-02, 3.73050630e-01, 1.24365047e-01,
       2.36892030e-01, 3.73050630e-01, 5.42502515e-02, 2.59844452e-01,
       1.05529182e-01, 3.41793507e-01, 3.73050630e-01, 6.39047325e-02,
       3.47049177e-01, 1.84671029e-01, 2.08624944e-01, 1.05731271e-01,
       2.98085451e-01, 3.49260807e-01, 7.02811927e-02, 2.88766846e-02,
       3.16942692e-01, 3.51192206e-01, 1.41602308e-01, 5.94808273e-02,
       1.81756541e-02, 3.73050630e-01, 7.83352032e-02, 3.73050630e-01,
       2.51945388e-02, 1.16192564e-01, 3.10576826e-01, 1.20513588e-01,
       6.28672242e-02, 3.67764175e-01, 1.99841887e-01, 2.54230469e-01,
       1.65428631e-02, 1.93745364e-02, 1.11264423e-01, 2.59370115e-02,
       3.73050630e-01, 1.00121208e-01, 3.37236613e-01, 4.66302820e-02,
       3.73050630e-01, 3.73050630e-01, 2.04334229e-01, 3.73050630e-01,
       3.54762524e-01, 7.25384802e-02, 1.71467081e-01, 1.48987118e-02,
       1.05380885e-01, 1.50699764e-01, 2.95056522e-01, 4.74963412e-02,
       2.24543568e-02, 1.01020820e-01, 2.75603265e-01, 3.73050630e-01,
       3.54959488e-01, 3.56546074e-01, 3.07260394e-01, 3.46352682e-02,
       2.37730239e-02, 3.22792083e-01, 3.00427884e-01, 9.38929711e-03,
       3.63578558e-01, 2.83863395e-01, 2.66919702e-01, 2.87771553e-01,
       5.74368238e-02, 3.10752448e-02, 1.97081547e-02, 4.53509763e-02,
       3.25727701e-01, 2.96037704e-01, 6.74279109e-02, 9.41517651e-02,
       1.40434936e-01, 3.53662163e-01, 3.29238087e-01, 3.73050630e-01,
       1.08317979e-01, 1.18475489e-01, 2.47117251e-01, 3.44952434e-01,
       3.73050630e-01, 3.73050630e-01, 1.37863606e-01, 3.63260895e-01,
       3.73050630e-01, 8.19722489e-02, 3.44353914e-01, 2.07418129e-02,
       2.56352991e-01, 9.00806040e-02, 1.52423223e-02, 7.00635538e-02,
       2.67410159e-01, 3.29525657e-02, 3.48251700e-01, 3.47640902e-01,
       3.73050630e-01, 1.09831773e-01, 3.73050630e-01, 1.91124052e-01,
       2.65719295e-01, 1.95793882e-01, 7.72810504e-02, 1.62555084e-01,
       5.26951365e-02, 5.15156500e-02, 1.10551096e-01, 1.18974507e-01,
       1.56599462e-01, 3.73050630e-01, 8.48664939e-02, 3.73050630e-01,
       2.45638080e-02, 3.55234928e-02, 3.73050630e-01, 3.74983884e-02,
       9.55556780e-02, 4.07391824e-02, 2.11125001e-01, 3.73050630e-01,
       2.40769982e-01, 3.73050630e-01, 3.37550402e-01, 3.23531240e-01,
       3.73050630e-01, 3.73050630e-01, 1.87692851e-01, 3.73050630e-01,
       2.27890149e-01, 4.98917997e-02, 3.73050630e-01, 1.43488258e-01,
       1.86745405e-01, 1.15060462e-02, 3.73050630e-01, 3.00100416e-01,
       3.73050630e-01, 3.52171957e-01, 3.54933321e-01, 1.53380781e-01,
       1.70203988e-02, 1.56509131e-02, 1.35498896e-01, 1.25340566e-01,
       3.19197863e-01, 3.57173383e-01, 2.90117767e-02, 3.14946979e-01,
       1.45818507e-02, 4.53999452e-02, 7.48549327e-02, 2.10886687e-01,
       5.45841679e-02, 3.67850840e-01, 1.38646469e-01, 4.63514328e-02,
       3.61622214e-01, 3.52980524e-01, 7.67544061e-02, 3.73050630e-01,
       8.03308096e-03, 1.78554177e-01, 5.12527265e-02, 1.63118586e-01,
       1.75332539e-02, 3.73050630e-01, 5.10589331e-02, 3.47787231e-01,
       2.05054551e-01, 1.79035962e-02, 9.65499505e-02, 2.36192092e-01,
       3.73050630e-01, 2.22985730e-01, 3.10844064e-01, 2.79274315e-01,
       3.10634881e-01, 6.00004233e-02, 3.17753643e-01, 1.91934749e-01,
       2.51631886e-01, 3.52531783e-02, 2.22711377e-02, 1.25091031e-01,
       9.07109156e-02, 1.50791392e-01, 3.16862017e-02, 3.73050630e-01,
       2.65114576e-01, 2.26549491e-01, 3.58452469e-01, 2.28018954e-01,
       3.27431113e-01, 1.59160733e-01, 6.81160092e-02, 3.73050630e-01,
       2.97931343e-01, 1.01206079e-01, 1.51255270e-02, 1.72541186e-01,
       6.60610348e-02, 1.11329146e-01, 3.73050630e-01, 8.12318772e-02,
       3.73050630e-01, 1.51452705e-01, 2.04177171e-01, 7.85647482e-02,
       2.16777902e-02, 4.10204306e-02, 2.55808771e-01, 3.79626341e-02,
       3.73050630e-01, 3.50363940e-01, 4.79161665e-02, 8.09626840e-03,
       3.41306627e-01, 3.06493994e-02, 1.76253721e-01, 1.93493396e-01,
       3.73050630e-01, 7.50225931e-02, 3.73050630e-01, 8.71229172e-02,
       3.27139109e-01, 3.04743260e-01, 1.30176350e-01, 7.99568519e-02,
       2.16145113e-01, 1.29209995e-01, 3.89838442e-02, 1.24106079e-01,
       3.56940627e-01, 2.83459425e-01, 7.36338943e-02, 9.19156000e-02,
       5.96152842e-02, 1.57408908e-01, 3.68448466e-01, 2.71478057e-01,
       3.73050630e-01, 3.14961851e-01, 3.65136534e-01, 1.69455260e-01,
       1.38299555e-01, 8.47208053e-02, 1.33765042e-01, 2.64426917e-01,
       2.57666647e-01, 3.73050630e-01, 1.76199630e-01, 1.13198295e-01,
       4.93103787e-02, 1.21473953e-01, 3.20483416e-01, 2.13517711e-01,
       1.14756063e-01, 1.47232234e-01, 2.72298962e-01, 1.04898684e-01,
       3.91350575e-02, 1.11147709e-01, 6.10281974e-02, 3.01548213e-01,
       1.46866366e-01, 2.37310752e-01, 2.85821468e-01, 3.38750780e-02,
       1.59074113e-01, 1.19545739e-02, 4.53964137e-02, 1.58633798e-01,
       6.34871796e-02, 4.03711274e-02, 3.30545306e-01, 1.33651137e-01,
       2.65341789e-01, 6.95492700e-02, 7.42711350e-02, 2.71158218e-01,
       1.75172359e-01, 3.39893997e-02, 1.12696663e-01, 2.75946885e-01,
       1.54296905e-01, 1.53895274e-01, 3.73050630e-01, 3.53864506e-02,
       2.72765696e-01, 3.15924376e-01, 2.68860489e-01, 2.56012917e-01,
       6.04448430e-02, 1.91113338e-01, 3.29254627e-01, 2.10722893e-01,
       3.73050630e-01, 3.73050630e-01, 2.21054643e-01, 1.86078712e-01,
       2.81066950e-02, 3.60801965e-01, 6.66806772e-02, 8.63405764e-02,
       1.48318544e-01, 1.52841151e-01, 7.80419819e-03, 3.52689534e-01,
       3.73050630e-01, 8.11489597e-02, 2.85320878e-01, 1.13778628e-01,
       8.88809711e-02, 1.99092135e-01, 2.61457682e-01, 2.78357238e-01,
       8.54735747e-02, 1.16807520e-01, 1.33256033e-01, 3.24025542e-01,
       3.18393230e-01, 4.58385535e-02, 7.92773739e-02, 3.73050630e-01,
       8.26269463e-02, 1.20612502e-01, 1.14701450e-01, 9.02038291e-02,
       8.30211863e-02, 1.86914518e-01, 3.28354001e-01, 3.28340009e-02,
       1.81182817e-01, 3.73050630e-01, 3.54031831e-01, 2.89155632e-01,
       6.99727759e-02, 4.85028401e-02, 2.28307143e-01, 1.22295275e-01,
       3.73050630e-01, 7.98758119e-02, 3.67243975e-01, 1.26253828e-01,
       8.78486186e-02, 1.43927764e-02, 9.13256556e-02, 1.74594559e-02,
       3.10594171e-01, 3.21310192e-01, 1.52023211e-02, 1.41796976e-01,
       2.73117989e-01, 1.72285318e-01, 1.53886199e-01, 2.27064684e-01,
       1.65256441e-01, 3.69295865e-01, 6.88631088e-02, 2.47166708e-01,
       1.83261469e-01, 2.57017851e-01, 3.66980106e-01, 3.17451283e-02,
       1.69394314e-01, 3.73050630e-01, 1.22392491e-01, 2.11842939e-01,
       1.72987487e-02, 3.73050630e-01, 2.73866564e-01, 2.65774708e-02,
       2.75496095e-01, 3.47096503e-01, 3.21361482e-01, 9.38104838e-03,
       2.23056562e-02, 3.73050630e-01, 3.50878596e-01, 1.87263370e-01,
       6.68358356e-02, 2.59892363e-02, 3.57672662e-01, 4.44627032e-02,
       6.47726208e-02, 3.73050630e-01, 2.58288831e-01, 3.47765237e-01,
       3.73050630e-01, 2.59017885e-01, 3.73050630e-01, 3.72604489e-01,
       3.73050630e-01, 7.68813789e-02, 3.73050630e-01, 4.94949892e-02,
       5.39756790e-02, 3.56701836e-02, 1.42991701e-02, 2.06189342e-02,
       3.73050630e-01, 6.10270202e-02, 2.79452682e-01, 2.87726820e-01,
       1.28649950e-01, 3.86829451e-02, 1.42431483e-01, 5.94409294e-02,
       1.58847064e-01, 3.66323471e-01, 1.66153714e-01, 3.50699872e-01,
       5.77041507e-02, 2.09392216e-02, 1.11425795e-01, 3.73050630e-01,
       3.34669828e-01, 4.74209376e-02, 3.73050630e-01, 3.73050630e-01,
       2.96265967e-02, 1.16232283e-01, 3.13824296e-01, 3.73050630e-01,
       2.87201647e-02, 3.78975235e-02, 6.99728876e-02, 2.35432893e-01,
       2.89510727e-01, 3.73050630e-01, 3.12831670e-01, 1.82450652e-01,
       3.23727578e-01, 1.62742257e-01, 6.17172122e-02, 1.08837649e-01,
       9.39290971e-02, 1.69921428e-01, 3.53441805e-01, 2.69283175e-01,
       2.85868794e-01, 1.58855960e-01, 6.91236630e-02, 6.66508973e-02,
       3.73050630e-01, 3.31902951e-01, 1.75270244e-01, 1.07146323e-01,
       1.57444682e-02, 3.73050630e-01, 2.01881081e-02, 5.19878343e-02,
       1.38859143e-02, 5.75774722e-02, 3.73050630e-01, 2.61326451e-02,
       2.51157194e-01, 1.28845563e-02, 1.24435052e-01, 3.65624309e-01,
       4.58494574e-02, 9.83913690e-02, 4.51705158e-02, 3.73050630e-01,
       1.40842795e-01, 3.73050630e-01, 1.01262026e-01, 2.77100921e-01,
       1.33534512e-02, 7.35050365e-02, 1.97513420e-02, 4.31132205e-02,
       4.40376215e-02, 1.72974065e-01, 3.38525236e-01, 3.73050630e-01,
       1.23309165e-01, 2.92164415e-01, 7.47734159e-02, 9.64854732e-02,
       3.41345191e-01, 9.13945735e-02, 3.45282018e-01, 2.71438584e-02,
       3.73050630e-01, 4.17604633e-02, 1.16527537e-02, 1.99502423e-01,
       3.01952839e-01, 2.14986667e-01, 4.73663695e-02, 4.26926799e-02,
       3.79544683e-02, 1.48235038e-01, 3.71819556e-01, 3.73050630e-01,
       1.21472344e-01, 3.36072385e-01, 1.87023729e-01, 2.28290353e-02,
       1.74787808e-02, 5.92285320e-02, 3.73050630e-01, 3.62497151e-01,
       2.27955297e-01, 1.43038973e-01, 2.96612997e-02, 1.10294245e-01],
      dtype=float32)

In [36]:
y_test

2323    1
3686    0
2974    1
2992    1
468     1
       ..
911     0
809     0
2940    1
3710    0
3257    0
Name: approval, Length: 900, dtype: int64

In [37]:
output=pd.DataFrame({'Actual': y_test, 'Prediction':(pred>=0.5).astype(int)})

In [38]:
output

      Actual  Prediction
2323       1           0
3686       0           0
2974       1           0
2992       1           0
468        1           0
...      ...         ...
911        0           0
809        0           0
2940       1           0
3710       0           0
3257       0           0

[900 rows x 2 columns]