In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('insurance.csv')

In [4]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [6]:
df.duplicated().sum()

np.int64(1)

In [7]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.dropna(inplace=True)

In [11]:
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [12]:
df['sex'].unique()

array(['female', 'male'], dtype=object)

In [13]:
cat_columns = df.select_dtypes(include='object').columns

for col in cat_columns:
    unique_vals = df[col].unique()
    mapping_dict = {}
    i=1
    for val in unique_vals:
        mapping_dict[val]=i
        i+=1
    df[col] = df[col].map(mapping_dict)

In [14]:
df.dtypes

age           int64
sex           int64
bmi         float64
children      int64
smoker        int64
region        int64
charges     float64
dtype: object

In [15]:
df

      age  sex     bmi  children  smoker  region      charges
0      19    1  27.900         0       1       1  16884.92400
1      18    2  33.770         1       2       2   1725.55230
2      28    2  33.000         3       2       2   4449.46200
3      33    2  22.705         0       2       3  21984.47061
4      32    2  28.880         0       2       3   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    2  30.970         3       2       3  10600.54830
1334   18    1  31.920         0       2       4   2205.98080
1335   18    1  36.850         0       2       2   1629.83350
1336   21    1  25.800         0       2       1   2007.94500
1337   61    1  29.070         0       1       3  29141.36030

[1337 rows x 7 columns]

In [17]:
df.to_csv("clean_insurance.csv")

In [18]:
x=df.drop('charges',axis=1)
y=df[['charges']]

In [19]:
x

      age  sex     bmi  children  smoker  region
0      19    1  27.900         0       1       1
1      18    2  33.770         1       2       2
2      28    2  33.000         3       2       2
3      33    2  22.705         0       2       3
4      32    2  28.880         0       2       3
...   ...  ...     ...       ...     ...     ...
1333   50    2  30.970         3       2       3
1334   18    1  31.920         0       2       4
1335   18    1  36.850         0       2       2
1336   21    1  25.800         0       2       1
1337   61    1  29.070         0       1       3

[1337 rows x 6 columns]

In [20]:
y

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1337 rows x 1 columns]

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x, y, random_state=42, test_size=0.2)

In [22]:
x_train

      age  sex     bmi  children  smoker  region
1114   23    2  24.510         0       2       4
968    21    2  25.745         2       2       4
599    52    1  37.525         2       2       3
170    63    2  41.470         0       2       2
275    47    1  26.600         2       2       4
...   ...  ...     ...       ...     ...     ...
1096   51    1  34.960         2       1       4
1131   27    2  45.900         2       2       1
1295   20    2  22.000         1       2       1
861    38    1  28.000         3       2       1
1127   35    1  35.860         2       2       2

[1069 rows x 6 columns]

In [23]:
x_test

      age  sex     bmi  children  smoker  region
900    49    2  22.515         0       2       4
1064   29    1  25.600         4       2       1
1256   51    1  36.385         3       2       3
298    31    2  34.390         3       1       3
237    31    2  38.390         2       2       2
...   ...  ...     ...       ...     ...     ...
534    64    2  40.480         0       2       2
542    63    1  36.300         0       2       2
760    22    1  34.580         2       2       4
1284   61    2  36.300         1       1       1
1285   47    1  24.320         0       2       4

[268 rows x 6 columns]

In [28]:
x_test.shape, y_test.shape, x_train.shape, y_train.shape

((268, 6), (268, 1), (1069, 6), (1069, 1))

In [29]:
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
rfr =RandomForestRegressor()
rfr.fit(x_train, y_train)

c:\Users\disha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1363: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [30]:
rfr.score(x_test, y_test)

0.8840691062538851

In [31]:
rfr.score(x_train, y_train)

0.9751188065440478

In [34]:
rfr.predict(x_test)

array([ 9917.213513 ,  6490.7324528, 11888.7824731, 43318.1318628,
        7051.7790959,  9865.8515959, 38894.6646662,  2608.7223486,
        8835.0094119, 11223.9125061, 14752.4412053, 23431.768867 ,
       43791.1808448, 15394.0824809,  7133.2363754,  8744.6043049,
        6724.3550773, 39418.015175 ,  5152.931089 ,  4764.892465 ,
        3974.3245502, 21099.6638759, 10043.4021511, 20185.5989645,
       39536.2231565, 16488.8909008, 42884.94968  , 45932.471043 ,
       10868.8422867, 14414.9911493,  4617.9213359,  9420.3986377,
        3291.9817247, 14940.0329693, 47289.4093336,  9724.09277  ,
        8986.0846612,  5793.2459737, 23240.9694454,  8833.6615785,
        4180.868712 , 21377.3326233, 41612.9576326,  9603.902918 ,
        9079.3533429,  3365.7015313,  4378.0460215,  7766.8761666,
        5732.289452 , 10263.3703783,  5143.9796611,  9835.8428584,
       22639.1018135,  3887.7147955,  7716.8467114,  8725.2001432,
       11734.3297901,  7305.3744724, 41633.0222453,  7459.0841974,
       11197.5533829,  5301.356266 , 18843.4767243,  1755.6809505,
       13631.22787  , 13142.570664 ,  7206.7466051, 22464.970822 ,
       16880.048864 , 18506.8410197, 13534.9485649, 14649.019939 ,
        7596.2664438,  7089.4528352, 11945.5659613,  3504.5090751,
       14735.359439 ,  5578.1075087, 11684.314925 , 12804.458283 ,
        9897.3530867, 17942.5808157, 13850.8771913, 10416.0715966,
       28613.2457105, 14206.7662633,  3820.0419099,  2759.093174 ,
        6942.7181095,  3788.7813368, 14955.2962524, 17961.0299909,
        6079.8053373,  8579.5162072,  1762.231981 , 43775.3331285,
       12172.3354969,  9540.9490851,  3772.2023156,  9737.2599585,
       13741.1550826, 16809.1741923, 25064.5323706, 15630.9819641,
       40203.7002492,  1627.826905 , 40572.0100408, 19512.2539261,
       12781.3895878,  6435.6559904,  7154.647322 , 12721.7920496,
        7013.4662748,  6832.365503 ,  2350.0937428,  2152.7421225,
        3937.480319 ,  3635.903231 ,  2853.0008828, 13357.310211 ,
       43997.4799705,  5950.1358369,  7528.3525125,  6106.7876169,
        8806.9926139,  7250.0331863,  5755.5538255, 13383.9666973,
       39300.1519483, 48116.3078885, 28428.2507335, 10778.4476453,
        2640.4715784, 12211.233756 ,  6391.7190428, 12422.8687312,
       45394.6256487, 22211.8774812, 18513.420657 ,  4218.6243202,
        6041.8255802, 10114.4365057, 43601.3781244, 11925.5658305,
        1454.815299 ,  6365.7378362,  5475.8289934,  8320.0330521,
       43254.5943147, 13496.947742 ,  6764.2119236,  9649.2056645,
        6513.5786207, 14594.3675235,  7019.9493008, 36025.2017577,
       42919.4979892, 11096.0613063,  9844.4232846, 10107.8706242,
       11785.4348328,  6159.1691696, 12076.7180503, 12153.460608 ,
       43897.447349 , 40513.0022975, 10295.793109 , 19394.3773886,
        5323.3813528,  4559.1672425,  5024.2059253,  2426.3125335,
        3987.3423345, 14214.4863153,  9904.2940455, 16924.900278 ,
        2590.0614734,  8794.0177732,  9570.1420938,  9974.6910421,
       16550.9969078,  4434.0556553, 13430.3856447, 13040.6296221,
       39632.0678188, 12269.6490961,  4072.9023085,  4738.4961831,
        2050.4168895, 46732.5746464,  3261.2515241, 23324.466375 ,
       14853.761068 ,  5391.3161045,  2326.4426655,  8493.8854675,
       39403.2218468,  4377.2548034, 14032.3572673, 17174.2806827,
       34532.7818355, 19006.7505455,  5292.8987285, 10752.3398627,
       18774.2643799,  6969.7978328,  7837.8856466,  9195.4095555,
        6527.2895773, 41936.2822569, 23959.3133866,  9404.7878094,
        5162.9886299,  7156.6401679, 15796.8531584,  1642.818036 ,
        2683.64284  ,  8307.5562209, 11036.7367196,  7838.3154685,
        3779.7114924, 44856.8705158, 45339.5226141, 21468.8939264,
        9687.1135557, 46752.8437225, 41693.9646205,  9662.6864967,
       35582.8241157,  8103.0922874, 13146.019664 , 38235.671834 ,
        8362.0061418,  7327.3490628, 11710.1560374, 13284.7577244,
       14024.5123324,  1758.6946725,  3346.282201 ,  4177.5722622,
        5325.0191415,  3946.0131609,  6501.5942324, 12131.6469344,
        1647.320738 , 10454.852663 ,  5641.4772287,  8518.0843414,
        4736.8880424,  9642.398824 ,  6679.9631829, 11637.1543635,
       12998.0002095, 14710.4345592, 44496.1641445, 13991.80925  ,
       12723.2064516,  7828.7791483,  7870.7822681, 11154.2202389,
       37185.3761225, 46849.580527 , 17465.0629289, 14355.1027272,
       14499.3347982, 12437.2560323, 47857.9418619, 14665.9848244])

In [35]:
import joblib
joblib.dump(rfr, 'model.joblib')

['model.joblib']

In [36]:
model= joblib.load('model.joblib')